# Tiene que estar en la carpeta prometheus/conf
# Correr el siguiente comando en el bastion
# docker run -p9090:9090 -d --volume "$(pwd)/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:ro" --volume "prometheus_data:/opt/bitnami/prometheus/data" --name prometheus bitnami/prometheus:latest
# Y el siguiente en los ec2
# docker run -d --net="host" --pid="host" -v "/:/host:ro,rslave" quay.io/prometheus/node-exporter:latest


global:
  scrape_interval: 10s
  evaluation_interval: 10s
  #query_log_file: /opt/bitnami/prometheus/query.log

scrape_configs:
  - job_name: 'local'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2'
    ec2_sd_configs:
      - region: us-west-2
        access_key: AKIA2LAXJRGVZIGSGQ6I
        secret_key: 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
        port: 9100

#    relabel_configs:
#        # Only monitor instances with a Name starting with "SD Demo"
#      - source_labels: [__meta_ec2_tag_Name]
#        regex: prod_*
#        action: keep
#        # Use the instance ID as the instance label
#      - source_labels: [__meta_ec2_instance_id]
#        target_label: instance