---
- hosts: "{{ EC2_NAMES }}"
  become: true
  remote_user: ubuntu
  become_method: sudo
  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: "docker<5"
      become: yes
    - name: Setup more docker dependencies
      pip:
        name: "websocket-client<1"
      become: yes
    - name: Log into DockerHub
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"
    - name: Pull Project Image
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull
    - name: Create default containers
      docker_container:
        name: "{{ DOCKER_CONTAINER }}"
        image: "{{ DOCKER_IMAGE }}"
        state: started
        pull: true
        ports:
          - 80:3000