#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[Husky] pre-commit"
npx lint-staged
npm run test
if ! [ -x "$(command -v terraform)" ]; then
  echo 'Warning: terraform is not installed.' >&2
else
  cd terraform && terraform fmt
fi